[package]
name = "secret_handshake"
version = "0.1.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]

[dependencies]
sodiumoxide = "0.0.15"
libc = "0.2"
futures = "0.1.14"

[dev-dependencies]
partial-io = { version = "0.2.3", features = ["quickcheck"] }
quickcheck = "0.4.1"

[build-dependencies]
gcc = "0.3"
